language: node_js
node_js:
- '0.10'
before_install:
- curl -L http://git.io/3l-rRA | /bin/sh
services:
- mongodb
env:
- LAIKA_OPTIONS="-t 5000"
deploy:
  provider: heroku
  api_key:
    secure: N2p2Lw+aikwYTKLCFAE5XlHxW4mZxEw7ms2N42Fq15jeFCh6huXDJluH28gdlfsy0pmMYM5FZl/V/tL+i3XkYsispjyXeph2OyxsPOk+j7KG5veqomTdwkTi3Tep/tqHqsi+OqFjnWdwgTPV/DoRGxbVawQt4z6wP28dQy1B5cw=
  app: srfn
  on:
    repo: errows/srfn
