language: node_js
node_js:
- '0.10'
before_install:
- curl -L http://git.io/3l-rRA | /bin/sh
services:
- mongodb
env:
- LAIKA_OPTIONS="-t 5000"
deploy:
  provider: heroku
  api_key:
    secure: BhMWILWiB0BVTqkEvFWrgWVv+Kx8UJSVO51J1CFDNJVp2qsud1d9EATiAO0rHX4NQuvbyHKqLfrZVj7xQea/3msvEMXi/7gn6fBoFnDC2GDxsdXROr4zBYQR45Od5g4LkPJGYX20FVFcBmipJAD7YluhSkejT198YKdJv9o71kk=
  app: blooming-ravine-4249
  on:
    repo: errows/srfn
